package vista;

import clases.Actividad;
import clases.Lista;
import clases.Usuario;
import excepciones.ErrExtra;
import excepciones.ErrUpdate;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import modelo.DAO;

/**
 *
 * @author xDoble_Jx
 */
public class Detalles_Lista extends javax.swing.JDialog {

    private int posX, posY;
    private VMain vMain;
    private DAO dao;
    private Usuario usu;
    private Lista list;

    /**
     * Creates new form Lista
     */
    public Detalles_Lista(VMain vMain, boolean modal, DAO dao, Usuario usu, Lista list) {
        super(vMain, modal);

        this.vMain = vMain;
        this.dao = dao;
        this.usu = usu;
        this.list = list;
        initComponents();

        setBackground(new Color(0, 0, 0, 0));

        barraTareas.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                posX = e.getX();
                posY = e.getY();
            }
        });

        barraTareas.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent e) {
                int dx = e.getX() - posX;
                int dy = e.getY() - posY;
                setLocation(getLocation().x + dx, getLocation().y + dy);
            }
        });

        txtTitulo.setText(list.getTitulo());
        spTitulo.setBounds(spTitulo.getX(), spTitulo.getY(), txtTitulo.getWidth(), 10);
        cargarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new recursos.LookVentana.RoundPanel();
        barraTareas = new recursos.LookVentana.RoundPanel();
        btnSalir = new javax.swing.JButton();
        opciones = new recursos.LookVentana.RoundPanel();
        imgLogo = new javax.swing.JLabel();
        imgLetras = new javax.swing.JLabel();
        spTitulo = new javax.swing.JSeparator();
        txtTitulo = new javax.swing.JTextField();
        panelLista = new recursos.LookVentana.RoundPanel();
        scroll = new javax.swing.JScrollPane();
        jLista = new javax.swing.JList<>();
        panelFotos = new recursos.LookVentana.RoundPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        fondo.setBackground(new java.awt.Color(21, 21, 21));

        barraTareas.setBackground(new java.awt.Color(49, 51, 53));

        btnSalir.setBackground(barraTareas.getBackground());
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pantalla/btnSalir.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setFocusPainted(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barraTareasLayout = new javax.swing.GroupLayout(barraTareas);
        barraTareas.setLayout(barraTareasLayout);
        barraTareasLayout.setHorizontalGroup(
            barraTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraTareasLayout.createSequentialGroup()
                .addContainerGap(1378, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        barraTareasLayout.setVerticalGroup(
            barraTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraTareasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(6, 6, 6))
        );

        opciones.setBackground(new java.awt.Color(49, 51, 53));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pantalla/logo.png"))); // NOI18N

        imgLetras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pantalla/letras logo.png"))); // NOI18N

        spTitulo.setBackground(opciones.getBackground());
        spTitulo.setForeground(txtTitulo.getForeground());

        txtTitulo.setBackground(opciones.getBackground());
        txtTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(227, 227, 227));
        txtTitulo.setText("jTextField1");
        txtTitulo.setBorder(null);

        javax.swing.GroupLayout opcionesLayout = new javax.swing.GroupLayout(opciones);
        opciones.setLayout(opcionesLayout);
        opcionesLayout.setHorizontalGroup(
            opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(imgLogo)
                .addGap(6, 6, 6)
                .addComponent(imgLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addGroup(opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        opcionesLayout.setVerticalGroup(
            opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesLayout.createSequentialGroup()
                .addGroup(opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opcionesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(opcionesLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(opcionesLayout.createSequentialGroup()
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(imgLetras))))
                .addGap(21, 21, 21))
        );

        panelLista.setBackground(new java.awt.Color(49, 51, 53));

        scroll.setBorder(null);

        jLista.setBackground(panelLista.getBackground());
        jLista.setBorder(null);
        jLista.setForeground(new java.awt.Color(227, 227, 227));
        scroll.setViewportView(jLista);

        javax.swing.GroupLayout panelListaLayout = new javax.swing.GroupLayout(panelLista);
        panelLista.setLayout(panelListaLayout);
        panelListaLayout.setHorizontalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelListaLayout.setVerticalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelFotos.setBackground(new java.awt.Color(49, 51, 53));

        javax.swing.GroupLayout panelFotosLayout = new javax.swing.GroupLayout(panelFotos);
        panelFotos.setLayout(panelFotosLayout);
        panelFotosLayout.setHorizontalGroup(
            panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );
        panelFotosLayout.setVerticalGroup(
            panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraTareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(opciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(panelLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelFotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(barraTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(opciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        vMain.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private recursos.LookVentana.RoundPanel barraTareas;
    private javax.swing.JButton btnSalir;
    private recursos.LookVentana.RoundPanel fondo;
    private javax.swing.JLabel imgLetras;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JList<String> jLista;
    private recursos.LookVentana.RoundPanel opciones;
    private recursos.LookVentana.RoundPanel panelFotos;
    private recursos.LookVentana.RoundPanel panelLista;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JSeparator spTitulo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

    private void cargarLista() {
        DefaultListModel<String> listModel = new DefaultListModel<>();
        JList<String> lista = new JList<>(listModel);

        String tabs;

        for (Actividad a : list.getActividades()) {
            tabs = "";

            for (int i = 0; i < a.getTabulacion(); i++) {
                tabs += "\t";
            }
            listModel.addElement(tabs + a.getTitulo());
        }
    }

}
