package vista;

import clases.Usuario;
import modelo.DAO;

/**
 *
 * @author xDoble_Jx
 */
public class P_Dia extends javax.swing.JPanel {

    private DAO dao;
    private Usuario usu;

    /**
     * Creates new form PDIa
     */
    public P_Dia(DAO dao, Usuario usu) {
        this.dao = dao;
        this.usu = usu;
        initComponents();
        setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new recursos.LookVentana.RoundPanel();
        pFechas = new recursos.LookVentana.RoundPanel();
        lblInicio = new javax.swing.JLabel();
        txtIncio = new javax.swing.JTextField();
        spInicio = new javax.swing.JSeparator();
        lblFinal = new javax.swing.JLabel();
        txtFinal = new javax.swing.JTextField();
        spFinal = new javax.swing.JSeparator();
        pActividades = new recursos.LookVentana.RoundPanel();
        pPasos = new recursos.LookVentana.RoundPanel();
        pKm = new recursos.LookVentana.RoundPanel();
        pHoras = new recursos.LookVentana.RoundPanel();
        pKcal = new recursos.LookVentana.RoundPanel();
        pFotos = new recursos.LookVentana.RoundPanel();
        imgActividades = new javax.swing.JLabel();

        fondo.setBackground(new java.awt.Color(21, 21, 21));

        pFechas.setBackground(new java.awt.Color(49, 51, 53));

        lblInicio.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(227, 227, 227));
        lblInicio.setText("INICIO:");

        txtIncio.setBackground(pFechas.getBackground());
        txtIncio.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtIncio.setForeground(new java.awt.Color(227, 227, 227));
        txtIncio.setText("Fecha de inicio");
        txtIncio.setBorder(null);

        spInicio.setBackground(pFechas.getBackground());
        spInicio.setForeground(new java.awt.Color(227, 227, 227));

        lblFinal.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblFinal.setForeground(new java.awt.Color(227, 227, 227));
        lblFinal.setText("FINAL:");

        txtFinal.setBackground(pFechas.getBackground());
        txtFinal.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtFinal.setForeground(new java.awt.Color(227, 227, 227));
        txtFinal.setText("Fecha de final");
        txtFinal.setBorder(null);

        spFinal.setBackground(pFechas.getBackground());
        spFinal.setForeground(new java.awt.Color(227, 227, 227));

        javax.swing.GroupLayout pFechasLayout = new javax.swing.GroupLayout(pFechas);
        pFechas.setLayout(pFechasLayout);
        pFechasLayout.setHorizontalGroup(
            pFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFechasLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInicio)
                    .addGroup(pFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtIncio, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(164, 164, 164)
                .addGroup(pFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtFinal, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spFinal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFinal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pFechasLayout.setVerticalGroup(
            pFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFechasLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(pFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInicio)
                    .addComponent(lblFinal))
                .addGap(18, 18, 18)
                .addGroup(pFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFechasLayout.createSequentialGroup()
                        .addComponent(txtIncio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(spInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pFechasLayout.createSequentialGroup()
                        .addComponent(txtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(spFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        pActividades.setBackground(new java.awt.Color(49, 51, 53));
        pActividades.setPreferredSize(new java.awt.Dimension(483, 100));

        javax.swing.GroupLayout pPasosLayout = new javax.swing.GroupLayout(pPasos);
        pPasos.setLayout(pPasosLayout);
        pPasosLayout.setHorizontalGroup(
            pPasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pPasosLayout.setVerticalGroup(
            pPasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pKmLayout = new javax.swing.GroupLayout(pKm);
        pKm.setLayout(pKmLayout);
        pKmLayout.setHorizontalGroup(
            pKmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pKmLayout.setVerticalGroup(
            pKmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pHorasLayout = new javax.swing.GroupLayout(pHoras);
        pHoras.setLayout(pHorasLayout);
        pHorasLayout.setHorizontalGroup(
            pHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pHorasLayout.setVerticalGroup(
            pHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pKcalLayout = new javax.swing.GroupLayout(pKcal);
        pKcal.setLayout(pKcalLayout);
        pKcalLayout.setHorizontalGroup(
            pKcalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pKcalLayout.setVerticalGroup(
            pKcalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pActividadesLayout = new javax.swing.GroupLayout(pActividades);
        pActividades.setLayout(pActividadesLayout);
        pActividadesLayout.setHorizontalGroup(
            pActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pActividadesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pPasos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(pKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(pKcal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(pHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pActividadesLayout.setVerticalGroup(
            pActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pActividadesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pPasos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pKcal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pFotos.setBackground(new java.awt.Color(49, 51, 53));
        pFotos.setPreferredSize(new java.awt.Dimension(483, 100));

        javax.swing.GroupLayout pFotosLayout = new javax.swing.GroupLayout(pFotos);
        pFotos.setLayout(pFotosLayout);
        pFotosLayout.setHorizontalGroup(
            pFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFotosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(imgActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pFotosLayout.setVerticalGroup(
            pFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFotosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(imgActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(pActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(pFotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pFechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(pFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pActividades, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addComponent(pFotos, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private recursos.LookVentana.RoundPanel fondo;
    private javax.swing.JLabel imgActividades;
    private javax.swing.JLabel lblFinal;
    private javax.swing.JLabel lblInicio;
    private recursos.LookVentana.RoundPanel pActividades;
    private recursos.LookVentana.RoundPanel pFechas;
    private recursos.LookVentana.RoundPanel pFotos;
    private recursos.LookVentana.RoundPanel pHoras;
    private recursos.LookVentana.RoundPanel pKcal;
    private recursos.LookVentana.RoundPanel pKm;
    private recursos.LookVentana.RoundPanel pPasos;
    private javax.swing.JSeparator spFinal;
    private javax.swing.JSeparator spInicio;
    private javax.swing.JTextField txtFinal;
    private javax.swing.JTextField txtIncio;
    // End of variables declaration//GEN-END:variables
}
