package vista;

import clases.Usuario;
import java.awt.Color;
import modelo.DAO;

/**
 *
 * @author xDoble_Jx
 */
public class P_Inicio extends javax.swing.JPanel {

    private DAO dao;
    private Usuario usu;

    /**
     * Creates new form PInicio
     */
    public P_Inicio(DAO dao, Usuario usu) {
        this.dao = dao;
        this.usu = usu;
        initComponents();
        setOpaque(true);
        setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new recursos.LookVentana.RoundPanel();
        pGrafico = new recursos.LookVentana.RoundPanel();
        pDatos = new recursos.LookVentana.RoundPanel();
        pPasos = new recursos.LookVentana.RoundPanel();
        pKm = new recursos.LookVentana.RoundPanel();
        pHoras = new recursos.LookVentana.RoundPanel();
        pKcal = new recursos.LookVentana.RoundPanel();

        fondo.setBackground(new java.awt.Color(21, 21, 21));

        pGrafico.setBackground(new java.awt.Color(49, 51, 53));

        javax.swing.GroupLayout pGraficoLayout = new javax.swing.GroupLayout(pGrafico);
        pGrafico.setLayout(pGraficoLayout);
        pGraficoLayout.setHorizontalGroup(
            pGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pGraficoLayout.setVerticalGroup(
            pGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        pDatos.setBackground(new java.awt.Color(49, 51, 53));

        pPasos.setBackground(new java.awt.Color(59, 61, 63));
        pPasos.setPreferredSize(new java.awt.Dimension(225, 139));

        javax.swing.GroupLayout pPasosLayout = new javax.swing.GroupLayout(pPasos);
        pPasos.setLayout(pPasosLayout);
        pPasosLayout.setHorizontalGroup(
            pPasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        pPasosLayout.setVerticalGroup(
            pPasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pKm.setBackground(new java.awt.Color(59, 61, 63));
        pKm.setPreferredSize(new java.awt.Dimension(225, 139));

        javax.swing.GroupLayout pKmLayout = new javax.swing.GroupLayout(pKm);
        pKm.setLayout(pKmLayout);
        pKmLayout.setHorizontalGroup(
            pKmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        pKmLayout.setVerticalGroup(
            pKmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );

        pHoras.setBackground(new java.awt.Color(59, 61, 63));
        pHoras.setPreferredSize(new java.awt.Dimension(225, 139));

        javax.swing.GroupLayout pHorasLayout = new javax.swing.GroupLayout(pHoras);
        pHoras.setLayout(pHorasLayout);
        pHorasLayout.setHorizontalGroup(
            pHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        pHorasLayout.setVerticalGroup(
            pHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pKcal.setBackground(new java.awt.Color(59, 61, 63));
        pKcal.setPreferredSize(new java.awt.Dimension(225, 139));

        javax.swing.GroupLayout pKcalLayout = new javax.swing.GroupLayout(pKcal);
        pKcal.setLayout(pKcalLayout);
        pKcalLayout.setHorizontalGroup(
            pKcalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        pKcalLayout.setVerticalGroup(
            pKcalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pDatosLayout = new javax.swing.GroupLayout(pDatos);
        pDatos.setLayout(pDatosLayout);
        pDatosLayout.setHorizontalGroup(
            pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pPasos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pKcal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pDatosLayout.setVerticalGroup(
            pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDatosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pPasos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pKm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pKcal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pHoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addComponent(pDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(pGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private recursos.LookVentana.RoundPanel fondo;
    private recursos.LookVentana.RoundPanel pDatos;
    private recursos.LookVentana.RoundPanel pGrafico;
    private recursos.LookVentana.RoundPanel pHoras;
    private recursos.LookVentana.RoundPanel pKcal;
    private recursos.LookVentana.RoundPanel pKm;
    private recursos.LookVentana.RoundPanel pPasos;
    // End of variables declaration//GEN-END:variables
}
