package vista;

import clases.Actividad;
import clases.Lista;
import clases.Usuario;
import excepciones.ErrExtra;
import excepciones.ErrInsert;
import excepciones.ErrSelect;
import java.awt.Color;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import modelo.DAO;

/**
 *
 * @author xDoble_Jx
 */
public class P_Listas extends javax.swing.JPanel {

    private VMain vMain;
    private DAO dao;
    private Usuario usu;

    private List<Lista> listas;

    /**
     * Creates new form PLista
     */
    public P_Listas(VMain vMain, DAO dao, Usuario usu) {
        this.vMain = vMain;
        this.dao = dao;
        this.usu = usu;
        initComponents();
        setOpaque(true);
        setBackground(new Color(0, 0, 0, 0));

        try {
            listas = dao.listarListasUsuario(usu.getId_usuario());

            for (int i = 0; i < listas.size(); i++) {
                panel.add(new PreviewLista(vMain, dao, usu, listas.get(i)));
                System.out.println();
            }
        } catch (ErrExtra ex) {
            ex.mostrarError();
        } catch (ErrSelect ex) {
            ex.mostrarError();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAniadirLista = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAniadirLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pantalla/boton-agregar.png"))); // NOI18N
        btnAniadirLista.setBorder(null);
        btnAniadirLista.setContentAreaFilled(false);
        btnAniadirLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirListaActionPerformed(evt);
            }
        });
        add(btnAniadirLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 618, 64, 64));

        scroll.setBackground(new java.awt.Color(21, 21, 21));
        scroll.setBorder(null);
        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.setAutoscrolls(true);
        scroll.setOpaque(false);

        panel.setBackground(scroll.getBackground());
        panel.setAutoscrolls(true);
        panel.setLayout(new java.awt.GridLayout(0, 3));
        scroll.setViewportView(panel);

        add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAniadirListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirListaActionPerformed
        try {
            String titulo = JOptionPane.showInputDialog(this, "Introduce el titulo de la lista");
            Lista list = new Lista();
            list.setId_lista(dao.generarIdLista());
            list.setTitulo(titulo);
            list.setDescripcion(null);
            list.setUsuario(usu.getId_usuario());
            list.setActividades(new ArrayList<Actividad>());

            dao.insertarLista(list);
            Detalles_Lista lista = new Detalles_Lista(vMain, true, dao, usu, list);
            lista.setVisible(true);

            panel.add(new PreviewLista(vMain, dao, usu, list));
            repaint();
        } catch (ErrExtra ex) {
            ex.mostrarError();
        } catch (ErrSelect ex) {
            ex.mostrarError();
        } catch (ErrInsert ex) {
            ex.mostrarError();
        }
    }//GEN-LAST:event_btnAniadirListaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAniadirLista;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
