package vista;

import clases.Lista;
import clases.Usuario;
import java.awt.Color;
import modelo.DAO;

/**
 *
 * @author xDoble_Jx
 */
public class PreviewLista extends javax.swing.JPanel {

    private VMain vMain;
    private DAO dao;
    private Usuario usu;
    private Lista list;

    /**
     * Creates new form previewLista
     */
    public PreviewLista(VMain vMain, DAO dao, Usuario usu, Lista list) {
        this.vMain = vMain;
        this.dao = dao;
        this.usu = usu;
        this.list = list;
        initComponents();
        setOpaque(true);
        setBackground(new Color(0, 0, 0, 0));

        lblTtitulo.setText(list.getTitulo());
        txtDescripcion.setText(list.getDescripcion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new recursos.LookVentana.RoundPanel();
        lblTtitulo = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        fondo.setBackground(new java.awt.Color(49, 51, 53));

        lblTtitulo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTtitulo.setForeground(new java.awt.Color(227, 227, 227));
        lblTtitulo.setText("Lista 1");

        txtDescripcion.setEditable(false);
        txtDescripcion.setBackground(fondo.getBackground());
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(null);
        txtDescripcion.setOpaque(false);
        scroll.setViewportView(txtDescripcion);

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(lblTtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Detalles_Lista lista = new Detalles_Lista(vMain, true, dao, usu, list);
        lista.setVisible(true);

    }//GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private recursos.LookVentana.RoundPanel fondo;
    public javax.swing.JLabel lblTtitulo;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
